# MySQL.  Versions 4.1 and 5.0 are recommended.

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: migrations_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: migrations_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: migrations_staging
  username: migrations
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: migrations_app_db
  username: migrations
  password: "scyt0[stroam"
  host: mysql.dartmouth.edu
